trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
    - job: BuildJob
    steps:
        - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean compile'

- stage: Unit_Test
  dependsOn: Build
  jobs:
    - job: TestJob
    steps:
        - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'test'

- stage: SonarQube
  dependsOn: Unit_Test
  jobs:
    - job: SonarJob
    steps:
        - script: echo SonarQube Scan done

- stage: Dependency_Scan
  dependsOn: SonarQube
  jobs:
    - job: DepJob
    steps:
        - script: echo Dependency Scan done

- stage: Package
  dependsOn: Dependency_Scan
  jobs:
    - job: PackageJob
    steps:
        - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package'
