trigger:
- main
pool:
  vmImage: ubuntu-latest
stages:
- stage: Build
  jobs:
    - job: BuildJob
    steps:
        - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'
        jdkVersionOption: '1.17'
- stage: Test
  dependsOn: Build
  jobs:
    - job: TestJob
    steps:
        - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'test'
        jdkVersionOption: '1.17'
- stage: SecurityScan
  dependsOn: Test
  jobs:
    - job: Scan
    steps:
        - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'verify'
        jdkVersionOption: '1.17'
