trigger:
- main
pool:
  vmImage: 'ubuntu-latest'
steps:
- script: echo "Build done"
  displayName: Build
- script: echo "Test done"
  displayName: Test
- script: echo "SonarQube done"
  displayName: SonarQube
- script: echo "Dependency Scan done"
  displayName: Dependency_Scan
- script: echo "Package done"
  displayName: Package